#!/bin/bash
## проверка на root

var=$(whoami)
echo $var       #для проверки вывода (временно)

if  [ $var!="root" ]
        then
                echo "you will must be root"
        else
                sestatus | grep status

fi

## если SElinux выключен- включить? (eys/no?)
#if [ =no  ]
#	then
#		echo "goodbay"
# 	else
#		selinux-command-on 
#
#
#
#
## если включен- выключить? (yes/no?)
#if[  =no ]
#	then
#		echo "godbay"
#
#	else
#		selinux-command-off
#fi

## 
~                                                             
