#!/bin/bash
#help page
[ "$1" == "-h" ]&&{                           # если параметр равен "-h" 

		echo "++++++++++++++++++++++++++++++++++++++++++++"
		echo "* This script can enable or disable SELinux"
		echo "* You must be a root "
		echo "* After work script need reboot your system"
		echo "++++++++++++++++++++++++++++++++++++++++++++"
		exit
}
#
[ "$#" == 0 ]&&{                        # запуск работы скрипта без параметров
if [ $(whoami) != root ]; then          #check root           
		echo "you are $(whoami), but must to be root"
                echo 'type with"-h" for print help page '   
else
		var=$(sestatus | grep -i 'selinux status') # print  sestatus 
		echo $var
		echo '*************************'
		echo 'Current mode:' $(getenforce)
		echo '*************************'
		echo '/etc/selinux/config mode:' $(cat /etc/selinux/config | grep -i '^selinux=')
		echo '*************************'
fi
# условия работы скрипта
if  [[ $var == 'SELinux status:                 enabled' ]]; then # не знаю как сделать без табов
		echo  'If you want switch "off" SELinux - type "yes": '
		read a		
  if [ $a == "yes" ]; then
		sed -i "s/SELINUX=enforsing/SELINUX=disabled/" /etc/selinux/config # меняем файл конфигурации
		cat /etc/selinux/config | grep -i '^selinux='
  else 	
		echo "error"
		exit
  fi
 		echo "The system must be rebooted for the changes to take effect. reboot now?(y/n):"
		read reb
  if [ $reb == "y" ]; then
                reboot
  fi

elif [[ $var == 'SELinux status:                 disabled' ]]; then 
		echo 'If you want switch "on" SELinux - type "yes": '
		read b
 if [ $b == "yes" ]; then
	        sed -i "s/SELINUX=disabled/SELINUX=enforsing/" /etc/selinux/config
		setenforce 1                                     # вот это не работает, не понимаю как из скрипта запускать команды с параметрами. $(setenforce 1) ? так же не работает
		cat /etc/selinux/config | grep -i '^selinux='		
 else		
 		echo "error"
		exit
 fi
		echo "The system must be rebooted for the changes to take effect. reboot now?(y/n):"
		read reb
 if [ $reb == "y" ]; then
                reboot
 fi
fi

} 
