#!/bin/bash
# helppage

[ "$1" == "-h" ]&&{                           # если параметр равен "-h" 
		echo '+-+-+-+-+-+-+'
		echo "This is help page"
		exit
}
#
[ "$#" == 0 ]&&{			#Если скрипт не получает входных параметров
if [ $(whoami) != root ]                    #           
	then                                #           
		echo "you are "$(whoami)    # check root           
		echo "but must to be root"
                echo 'type with"-h" for print help page '   
	else
		var=$(sestatus | grep -i 'selinux status') # print  sestatus 
		echo $var
		echo '*************************'
		echo 'Current mode:' $(getenforce)
		echo '*************************'
		echo '/etc/selinux/config mode:' $(cat /etc/selinux/config | grep -i '^selinux=')
		echo '*************************'
 fi
# условия работы скрипта
 if  [[ $var == 'SELinux status:                 enabled' ]] # сдесь не знаю как правильно сделать без табов
	then 
		echo -n 'If you want switch "off" SELinux - type "yes": '
		read a		
   if [ $a == "yes" ]
	then
		sed -i "s/SELINUX=enforsing/SELINUX=disabled/" /etc/selinux/config
		cat /etc/selinux/config | grep -i '^selinux='
	else 	
		echo "error"
 fi
 elif [[ $var == 'SELinux status:                 disabled' ]]
        then 
		echo 'If you want switch "on" SELinux - type "yes": '
		read b
 if [ $b == "yes" ]
	then
	        sed -i "s/SELINUX=disabled/SELINUX=enforsing/" /etc/selinux/config
		cat /etc/selinux/config | grep -i '^selinux='		
        else
		echo "error"
  fi
 fi
}



# собрать кострукцию опроса, -ok
# написать команду sed(замена строки) - ok
# добавить 
